// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysqlmodel

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	UserID            int64     `gorm:"column:userId;primaryKey;autoIncrement:true" json:"userId"`
	Avatar            string    `gorm:"column:avatar" json:"avatar"`
	FullName          string    `gorm:"column:fullName;not null" json:"fullName"`
	Bio               string    `gorm:"column:bio" json:"bio"`
	UserName          string    `gorm:"column:userName;not null" json:"userName"`
	Password          string    `gorm:"column:password;not null" json:"password"`
	HomeLocation      string    `gorm:"column:homeLocation;not null" json:"homeLocation"`
	HomeCoordinate    string    `gorm:"column:homeCoordinate;not null" json:"homeCoordinate"`
	CurrentLocation   string    `gorm:"column:currentLocation;not null" json:"currentLocation"`
	CurrentCoordinate string    `gorm:"column:currentCoordinate;not null" json:"currentCoordinate"`
	Rank              int64     `gorm:"column:rank;not null" json:"rank"`
	TotalSilver       int64     `gorm:"column:totalSilver;not null" json:"totalSilver"`
	TotalGold         int64     `gorm:"column:totalGold;not null" json:"totalGold"`
	TotalDiamond      int64     `gorm:"column:totalDiamond;not null" json:"totalDiamond"`
	TotalQuestPlayed  int64     `gorm:"column:totalQuestPlayed;not null" json:"totalQuestPlayed"`
	TotalQuestCreated int64     `gorm:"column:totalQuestCreated;not null" json:"totalQuestCreated"`
	TotalFollowers    int64     `gorm:"column:totalFollowers;not null" json:"totalFollowers"`
	TotalFollowees    int64     `gorm:"column:totalFollowees;not null" json:"totalFollowees"`
	DeviceID          string    `gorm:"column:deviceId;not null" json:"deviceId"`
	DeviceName        string    `gorm:"column:deviceName;not null" json:"deviceName"`
	FcmToken          string    `gorm:"column:fcmToken;not null" json:"fcmToken"`
	LanguageCode      string    `gorm:"column:languageCode;not null;default:en" json:"languageCode"`
	CreatedAt         time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt         time.Time `gorm:"column:updatedAt;not null;default:CURRENT_TIMESTAMP" json:"updatedAt"`
	Status            string    `gorm:"column:status;not null;default:ACTIVE" json:"status"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
