package constant

// ACCESS TOKEN TYPE
const TOKEN_TYPE_AMIN = "ADMIN"
const TOKEN_TYPE_USER = "USER"
const TOKEN_TYPE_DRIVER = "DRIVER"

// ACCESS TOKEN PAYLOAD
const TOKEN_PAYLOAD = "TOKEN_PAYLOAD"
