package constant

// ACCESS TOKEN TYPE
const TOKEN_TYPE_ADMIN = "ADMIN"
const TOKEN_TYPE_SUBADMIN = "SUB_ADMIN"
const TOKEN_TYPE_USER = "USER"
const TOKEN_TYPE_DRIVER = "DRIVER"

// ACCESS TOKEN PAYLOAD
const TOKEN_PAYLOAD = "TOKEN_PAYLOAD"
